# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

# Required by RNFirebase
pod 'Firebase/Core', '~> 5.3.0'
pod 'Firebase/Firestore', '~> 5.3.0'
pod 'Firebase/Auth', '~> 5.3.0'

pod 'React', :path => '../node_modules/react-native', :subspecs => [
  'RCTImage'
]
pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'FBSDKCoreKit'

target 'champs_diary' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for champs_diary

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'champs_diaryTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
